.PHONY: all
.PHONY: install
.PHONY: clean

ISP_PREFIX ?= $(HOME)/.local/isp/

all: Makefile
	$(MAKE)

Makefile:
	./bootstrap
	./configure --prefix=$(ISP_PREFIX) --enable-remote-bitbang --enable-jtag_vpi --enable-ftdi --enable-doxygen-pdf

install:
	$(MAKE) install

clean: Makefile
	$(MAKE) clean
